service: go-lambda-dynamo

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: ${opt:stage, self:provider.stage}-serverless-test
  ecr:
    images:
      go-lambda-dynamo_example:
        path: ./
        file: Dockerfile
      dev-cognito-lambda:
        path: ./
        file: Dockerfile.cognito
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - cognito-idp:AdminConfirmSignUp
      Resource: "*"

functions:
  getDictionaryItems:
    image:
        name: go-lambda-dynamo_example
    events:
      - http:
          path: dictionary
          method: get
          cors: true 
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
  addDictionaryItems:
    image:
        name: go-lambda-dynamo_example
    events:
      - http:
          path: dictionary
          method: post
          cors: true 
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
  confirmSignUp:
    image:
        name: dev-cognito-lambda
    events:
      - cognitoUserPool:
          pool: Dev_RedstoneCircuitDictonary_UserPool
          trigger: PreSignUp
    environment:
      REGION: ${self:provider.region}

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: Number
            AttributeType: N
          - AttributeName: word
            AttributeType: S
        KeySchema:
          - AttributeName: Number
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: word_index
            KeySchema: 
              - AttributeName: word
                KeyType: HASH
            Projection: 
              ProjectionType: ALL            
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: Dev_RedstoneCircuitDictonary_UserPool
        UsernameConfiguration:
          CaseSensitive: false
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: false
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            TemporaryPasswordValidityDays: 7
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        MfaConfiguration: OFF
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: false
          DeviceOnlyRememberedOnUserPrompt: false

    CognitoUserPoolGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: AdminGroup
        UserPoolId:
          Ref: CognitoUserPool
        Description: "Group for admin users"
        Precedence: 1

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: Dev_RedstoneCircuitDictonary
        UserPoolId:
          Ref: CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_CUSTOM_AUTH
        SupportedIdentityProviders:
          - COGNITO
