service: RedstoneCircuitDictionary

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: ${opt:stage, 'dev'}-redstoneCircuitDictionary-words
    REGION: ${self:provider.region}
    COGNITO_POOL_ID: !Ref CognitoUserPool
    BUCKET_NAME: ${opt:stage, 'dev'}-redstone-circuit-dictionary-files-upload
  ecr:
    images:
      redstone-circuit-dictionary-https:
        path: .
        file: docs/Dockerfile.https
      redstone-circuit-dictionary-cognito:
        path: .
        file: docs/Dockerfile.cognito
      redstone-circuit-dictionary-files-upload:
        path: .
        file: docs/Dockerfile.s3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/poster_index"
    - Effect: Allow
      Action:
        - cognito-idp:AdminConfirmSignUp
      Resource: "arn:aws:cognito-idp:${self:provider.region}:${aws:accountId}:userpool/${self:resources.Resources.CognitoUserPool.Properties.UserPoolName}"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*

functions:
  httpHandler:
    image:
        name: redstone-circuit-dictionary-https
    events:
      - http:
          path: dictionary
          method: get
      - http:
          path: dictionary
          method: post
          cors: 
            origins:
              - 'http://localhost:3000'
              - 'https://staging.d1631t3ap8rd8k.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
              - x-processing-type1
              - x-processing-type2
            allowCredentials: true
      - http:
          path: dictionary/{id}
          method: put
          cors: 
            origins:
              - 'http://localhost:3000'
              - 'https://staging.d1631t3ap8rd8k.amplifyapp.com'
            headers:
              - Content-Type
              - Authorization
              - x-processing-type1
              - x-processing-type2
            allowCredentials: true
      - http:
          path: dictionary/{id}
          method: delete
          cors:
            origins:
              - 'http://localhost:3000' 
              - 'https://staging.d1631t3ap8rd8k.amplifyapp.com' 
            headers:
              - Content-Type
              - Authorization
              - x-processing-type1
              - x-processing-type2
            allowCredentials: true
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
  confirmSignUp:
    image:
        name: redstone-circuit-dictionary-cognito
    events:
      - cognitoUserPool:
          pool: ${opt:stage, 'dev'}-redstoneCircuitDictionary-userPool
          trigger: PreSignUp
          existing: true
  http-S3:
    image:
      name: redstone-circuit-dictionary-files-upload
    events:
      - http:
          path: /files-upload
          method: get
          cors:
            origins:
              - 'http://localhost:3000'
              - 'https://staging.d1631t3ap8rd8k.amplifyapp.com'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false
          request:
            parameters:
              querystrings:
                filename: true  # クエリパラメータでファイル名を指定
    environment:
      BUCKET_NAME: !Ref S3Bucket

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: poster
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: poster_index
            KeySchema: 
              - AttributeName: poster
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection: 
              ProjectionType: ALL            
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${opt:stage, 'dev'}-redstoneCircuitDictionary-userPool
        UsernameConfiguration:
          CaseSensitive: false
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: false
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            TemporaryPasswordValidityDays: 7
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        MfaConfiguration: OFF
        DeviceConfiguration:
          ChallengeRequiredOnNewDevice: false
          DeviceOnlyRememberedOnUserPrompt: false
    CognitoUserPoolGroup:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: AdminGroup
        UserPoolId: !Ref CognitoUserPool
        Description: "Group for admin users"
        Precedence: 1
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${opt:stage, 'dev'}-redstoneCircuitDictionary
        UserPoolId: !Ref CognitoUserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_CUSTOM_AUTH
        SupportedIdentityProviders:
          - COGNITO

    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - 'http://localhost:3000'  # フロントエンドからのオリジンを指定
                - 'https://staging.d1631t3ap8rd8k.amplifyapp.com'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              AllowedHeaders:
                - "Content-Type"
              MaxAge: 3000
    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: S3AccessPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - s3:GetObject
                    - s3:PutBucketPolicy
                  Resource: arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*

plugins:
  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
      # Dockerfileは基本的に親のディレクトリを参照できないので、デプロイ前に複数のDockerイメージをビルドする
      before:deploy:deploy: |
        docker build -t redstone-circuit-dictionary-https -f ./docs/Dockerfile.https .
        docker build -t redstone-circuit-dictionary-cognito -f ./docs/Dockerfile.cognito . 
        docker build -t redstone-circuit-dictionary-files-upload -f ./docs/Dockerfile.s3 . 
